### ISSUE TITLE
Invalid Face Reference

### ISSUE THREAD

**Issue by jmquigley** [jrblevin/markdown-mode#234] opened 2017-08-05 21:20 UTC
The mode is generating the following error over and over:

`Invalid face reference: markdown-header-face-7 [105 times]`

If I scroll through the document it generates this error hundreds of times.  It looks like it is no longer scaling any of the markdown headers either.

Emacs 26.0.5 (in console, using WSL)
Markdown mode latest: [20170803.1101](https://melpa.org/#/markdown-mode)

**Comment by jrblevin** [comment] 2017-08-06 00:06
Does your test file by chance have level-7 headings? HTML, and hence Markdown, only define h1 through h6, so that's all `markdown-mode` tries to handle.

The bug here most likely is that `markdown-mode` is trying to apply a non-existent face.

**Comment by jmquigley** [comment] 2017-08-06 02:56
The readme file that I'm working on has a max level header of 4.

https://raw.githubusercontent.com/jmquigley/gadgets/master/README.md

**Comment by jrblevin** [comment] 2017-08-06 12:18
Thanks for sending the file. I can reproduce this and will take a closer look soon.

**Comment by jrblevin** [comment] 2017-08-30 00:53
It turns out that this was related to the lack of whitespace between some of the headings and the code blocks that followed. It should be fixed now, but let me know if you still see the error.

**Closed** 2017-08-30 00:53 UTC
Labels: bug

**Comment by jmquigley** [comment] 2017-08-30 17:05
This fixed the issue.  Thanks.

**Comment by prosoitos** [comment] 2024-01-23 10:25
I am having a similar issue with the natively compiled version of Emacs:

```elisp
(jit-lock--run-functions 995 2930) [UNPR HOST <my-file>]: Invalid face: markdown-header-face-7
```
