### ISSUE TITLE
Emacs hangs with some content

### ISSUE THREAD

**Issue by DougHaber** [jrblevin/markdown-mode#406] opened 2019-07-10 15:05 UTC
## Expected Behavior

In this case, the expected behavior is to not cause Emacs to hang and not use 100% of the CPU.

## Actual Behavior

When adding a certain type of content into a markdown document, Emacs hangs and uses 100% of the CPU.  I did attempt to wait it out, but after a few minutes it was still hung.  Emacs needed to be SIGTERM'd.

## Steps to Reproduce

1. Create a `test.md` file with this single line in it:
    ```markdown
    --tag-specifications ResourceType=string,Tags=[{Key=foo,Value=bar}, {Key=foo,Value=bar},{Key=foo,Value=bar},{Key=foo,Value=bar},{Key=foo,Value=bar},{Key=foo,Value=bar}]
    ```
    
    (Note, the behavior is the same regardless of whether that line is in a markdown code block. 
 When I originally encountered this, it was.)

2.  Open the test.md file:
    ```sh
    emacs -Q --load markdown-mode.el test.md
    ```

## Software Versions

- Markdown Mode: `markdown-mode, version 2.3`
- Emacs: `GNU Emacs 24.5.1 (x86_64-pc-linux-gnu) of 2017-09-12 on hullmann, modified by Debian`
- OS: tried `Debian Stretch` and `macOS Mojave` with same results

**Comment by syohex** [comment] 2020-04-29 02:44
Thanks for reporting issue. I have merged #452. Please check latest version

**Closed by syohex** 2020-04-29 02:44 UTC

**Comment by jschewebbn** [comment] 2020-11-03 18:33
I've applied this patch and the example works, however I've found another case that breaks markdown mode and causes emacs to peg the CPU.
```
2020-11-03/14:16:47.538/+0000 [DCOP-Aserver03.map.dcomp] DEBUG com.bbn.map.Controller.Aserver03.map.dcomp [] {}- Sharing DCOP information ImmutableDcopSharedInformation[ DcopSharedInformation [iterationMessageMap={}, asynchronousMessage=MessagePerIteration [sender=null, iteration=2, receiverMessageMap={A=FinalRCDiffDcopMessage [messageMap={TREE=[FinalRCDiffTree [pathToClient={}, selfRegionServices=[]]]}], B=FinalRCDiffDcopMessage [messageMap={C=[FinalRCDiffProposal [sender=null, root=null, sink=null, hop=2147483647, proposalCapacity=-1.7976931348623157E308]], G=[FinalRCDiffRequest [root=null, loadMap={}, hop=2147483647]]}], X=FinalRCDiffDcopMessage [messageMap={C=[FinalRCDiffProposal [sender=null, root=null, sink=null, hop=2147483647, proposalCapacity=-1.7976931348623157E308]], G=[FinalRCDiffRequest [root=null, loadMap={}, hop=2147483647]]}]}], constructed at=2020-11-03T14:16:47.538598] ]
```

**Comment by syohex** [comment] 2020-11-04 01:01
I cannot reproduce with above snippet. Did you use latest markdown-mode ? or Could you tell us how to reproduce in more detail ?

**Comment by jschewebbn** [comment] 2020-11-04 15:19
I'm using the flatpak install of emacs version 27.1. The markdown-version variable reports 2.4-dev. When I looked at the source for markdown-mode.el I saw that it did not have the code change from #452. So I applied that patch, rebuilt the elc and restarted emacs.

**Comment by syohex** [comment] 2020-11-04 23:51
Latest version is 2.5-dev. Could you try with latest version ? Some other changes may fix your issue.

**Comment by jschewebbn** [comment] 2020-11-05 13:44
Where can I find 2.5-dev? The github repository has 2.4 listed as the last release.

**Comment by syohex** [comment] 2020-11-05 13:49
https://github.com/jrblevin/markdown-mode/blob/master/markdown-mode.el
https://raw.githubusercontent.com/jrblevin/markdown-mode/master/markdown-mode.el

master branch version

**Comment by jschewebbn** [comment] 2020-11-05 14:00
That does indeed fix the issue. To be clear, I did the following to test
1. download el file from the link
1. start emacs with `emacs -q`
1. Used dired to open the directory where markdown-mode.el was downloaded
1. Loaded the file from dired
1. Opened a new markdown file and tested the text
