### ISSUE TITLE
(GFM) Often fails to properly detect start/end of PRE-formatted code blocks

### ISSUE THREAD

**Issue by mcandre** [jrblevin/markdown-mode#85] opened 2016-02-01 19:36 UTC
GFM often fails to detect the start and/or end of triple-backtick PRE-formatted code blocks.

Example:

https://raw.githubusercontent.com/mcandre/hello-thrift/master/README.md

**Comment by cosmicexplorer** [comment] 2016-02-07 01:41
Could you describe the issue in more detail? Which code blocks is it failing to detect? I'm using the current master right now and I think it seems to be detecting all of them just fine.

**Comment by jrblevin** [comment] 2016-02-17 18:05
Thanks to @cosmicexplorer, markdown-mode has improved font locking for fenced code blocks (triple backquote and other kinds). Could you please try again with the latest master version and let me know if this issue is resolved (and if not, perhaps a few more details would be helpful)?

**Comment by jrblevin** [comment] 2016-02-26 01:06
I'm assuming this has been fixed and am closing this issue. If you find it has not been fixed, please reopen and provide additional details needed to reproduce the issue.

**Closed by jrblevin** 2016-02-26 01:06 UTC

**Comment by Soreine** [comment] 2016-03-07 15:26
Hello, I came here for a similar problem. It seems that my installation of Emacs also fails to detect end/beginning of code blocks.
On my installation, when I open the [file content](https://raw.githubusercontent.com/mcandre/hello-thrift/master/README.md) given from the author of the issue in `gfm-mode`, everything looks good. But if I position my cursor at `(32,0)`, and insert a newline, then the next text and code blocks aren't highlighted correctly anymore.
Could you let me know if you experience a similar issue ? Otherwise I will share a minimal, reproducible configuration for the bug.
Thanks in advance

**Comment by jrblevin** [comment] 2016-03-07 19:14
I downloaded the new file linked above but still cannot reproduce this issue. Can you confirm that you are using the latest development version of markdown-mode? What is your Emacs version? Are you loading markdown-mode in isolation, without other minor modes?

**Comment by syohex** [comment] 2016-03-08 01:54
@Soreine I cannot reproduce too. Here is a gif animation with Emacs 24.5 and latest markdown-mode without other minor-modes.

![markdown-cb-highlight](https://cloud.githubusercontent.com/assets/554281/13589559/08de2c18-e51c-11e5-9565-dfb54fae6fef.gif)
