### ISSUE TITLE
Please wrap your modifications to display inside (with-silent-modifications; this makes file be marked as modified

### ISSUE THREAD

**Issue by abelardojarab** [jrblevin/markdown-mode#289] opened 2017-11-16 22:14 UTC
Please wrap your modifications to display inside (with-silent-modifications 

Your markdown-mode major mode keeps modifying the 'display' property and thus im getting C-h v buffer-undo-list

Value
((nil display nil 16535 . 16536)
 (nil display nil 16534 . 16535)
 (nil display nil 16189 . 16534)
 (nil display nil 16188 . 16189)
 (nil display nil 16001 . 16188)
 (nil display nil 15988 . 16001)
 (nil display nil 15843 . 15988)
 (nil display nil 15842 . 15843)
 (nil display nil 15838 . 15842)
 (nil display nil 15497 . 15838)
 (nil display nil 15496 . 15497)
 (nil display nil 15151 . 15496)

Can you please dont do this; this makes buffer be marked as modified

**Comment by jrblevin** [comment] 2017-11-17 12:02
I can't reproduce this, so can you give some more information to help me narrow down where this is happening? Which version of markdown-mode.el are you seeing this with? What sort of Markdown elements were in your buffer at those positions?

**Comment by abelardojarab** [comment] 2017-11-18 19:09
thanks a lot for the reply; I am engineer working for Altera/Intel. We want to write all documentation of our open-source project using markdown/sphinx

im using my current emacs-configuration from here:

https://github.com/abelardojarab/emacs-config

the problem im having is markdown-mode buffers get marked as modified every single time i visit them. easy way to reproduce this:
1. just open a markdown file with my configuration

-or-

1. open markdown file
2. save markdown file to get rid of the modification flag
3. switch to another buffer
4. switch back to the markdown file

do you think you can please take a look?

*** note ***
if i run emacs in console; no GUI this issue does not happen. so it seems it is an issue related with running in GUI. I am running emacs 25.3

please, please if you can take a look and sorry so much for bugging.

**Comment by abelardojarab** [comment] 2017-11-18 19:11
also, what theme/font are you using they look super professional. sorry to ask; either way the most critical/important part is please could you take a look on what is happening with the display property being modified....?

**Comment by abelardojarab** [comment] 2017-11-18 19:12
this *only* happens with markdown mode; it *doesnt* happen neither with org-mode; yaml-mode; json-mode; or any programming mode; it is **solely** happening with markdown-mode....

**Comment by jrblevin** [comment] 2017-11-19 02:47
Which version of markdown-mode.el are you seeing this with? Latest GitHub or MELPA? Or perhaps a previous stable version? If you’re not sure you can check with <kbd>M-x markdown-show-version</kbd>.

**Comment by abelardojarab** [comment] 2017-11-19 07:28
hi thanks again for taking a look, God bless you. im using the one from melpa

i fetch all my emacs packages using Cask

i tried switching to your lates stable release but the issue with display property being modified still was present.

**Comment by abelardojarab** [comment] 2017-11-19 07:29
this is my pointer to my Cask file

https://github.com/abelardojarab/emacs-config/blob/master/.emacs.d/Cask

**Comment by abelardojarab** [comment] 2017-11-19 07:31
and this my setup for markdown-mode
https://github.com/abelardojarab/emacs-config/blob/master/.emacs.d/setup/setup-markdown.el

as important information i tried disabling *all* hooks i added to markdown mode (flyspell, flycheck/proselint, orgtbl-mode, everything just plain markdown mode) and still the issue is happening

it *does not* happen in console mode though; only in GUI.

**Comment by jrblevin** [comment] 2017-11-19 13:33
> im using the one from melpa

Thanks for providing the version info.  Unfortunately, I still can't reproduce the issue. What I need to track down a bug are instructions to reproduce without local packages and settings. Try running Emacs like this and see if you still experience the problem:

```
emacs -Q -l ~/path/to/markdown-mode.el
```

> and this my setup for markdown-mode

I took a brief look at your configuration but I didn't notice anything obvious that might be causing the issue. I can't debug your local configuration in detail, but if the problem is due to an interaction with another package you're using, and if the issue is on the `markdown-mode` side, then I would be happy to try to fix that.

As an side, you should disable `orgtbl-mode` and the pipe table editing hack in your markdown-mode configuration: they are no longer needed since table editing is now included. Also, you may not need `polymode` depending on how you use it, since `markdown-mode` can fontify code blocks now.

> also, what theme/font are you using they look super professional.

In the README screenshot, it is a slightly modified variant of the default theme (darken the background a bit to contrast with white for the [book](https://leanpub.com/markdown-mode/)) with the [Operator Mono](https://www.typography.com/blog/introducing-operator) font.

**Comment by jrblevin** [comment] 2017-12-09 20:18
Since there's nothing actionable for `markdown-mode` right now I'm going to close this.  If you do zero in on an interaction with another package or a way to reproduce the issue, please feel free to reopen.

**Closed by jrblevin** 2017-12-09 20:18 UTC
Labels: unconfirmed
